<?
$dataCheck = $this->dataCheck;
?>

Вы не зарегистрированы, для продолжения авторизуйтесь</br>

<? if(!empty($dataCheck)): ?>
    <? foreach ($dataCheck as $error): ?>
        <div>
            <br>
            <b><?= $error; ?></b>
        </div>
    <? endforeach; ?>
<? endif; ?>

<form action="registr" method="post" enctype="multipart/form-data">
    <input type="hidden" name="command" value="registr">
    <p>
    Имя: <input type="text" name="name" value=""></br>
    </p>
    <p>
    Возраст: <input type="text" name="age" value=""></br>
    </p>
    <p>
    Опишите себя: <input type="text" name="description" value=""></br>
    </p>
    <p>
    Почта: <input type="email" name="email" value=""></br>
    </p>
    <p>
    Пароль: <input type="text" name="password" value=""></br>
    </p>
    <p>
    <input type="file" name="file"></br>
    </p>
    <input type="submit" value="Регистрация">
</form>