<form action="storage" method="post" enctype="multipart/form-data">
    <input type="file" name="file">
    <input type="submit">
</form>

<?

/*
require 'C:\OSPanel\domains\mvc2\vendor\autoload.php';
use Intervention\Image\ImageManager;

if(!$_FILES['file']){
    $manager = new ImageManager();
    $image = $manager->make($_FILES['file']['tmp_name'])
        ->resize(400, null, function ($pic) {
            $pic->aspectRatio();
        })
        ->save('../public/images/2.jpg');
}
*/

?>

